#pragma once

#include <juce_gui_basics/juce_gui_basics.h>
#include "ColorPalette.h"

namespace ssab
{
    // ------------------------------------------------------------------
    // Loads the two horror fonts from the embedded binary data and
    // exposes them as cached typefaces.
    // ------------------------------------------------------------------
    class SSABFonts
    {
    public:
        static SSABFonts& get()
        {
            static SSABFonts instance;
            return instance;
        }

        const juce::Font& getDisplayFont() const  { return displayFont; }
        const juce::Font& getBodyFont() const      { return bodyFont; }
        const juce::Font& getLabelFont() const     { return labelFont; }
        const juce::Font& getSmallFont() const     { return smallFont; }

    private:
        SSABFonts()
        {
            // Pull embedded fonts from BinaryData (auto-generated by juce_add_binary_data).
            // BinaryData::HorrorNightDrip_ttf, BinaryData::HorrorNightDrip_ttfSize
            // BinaryData::ShockHorror_otf,    BinaryData::ShockHorror_otfSize
            shockTypeface = loadTypeface("ShockHorror_otf",
                BinaryData::ShockHorror_otf, BinaryData::ShockHorror_otfSize);
            horrorTypeface = loadTypeface("HorrorNightDrip_ttf",
                BinaryData::HorrorNightDrip_ttf, BinaryData::HorrorNightDrip_ttfSize);

            displayFont = juce::Font(shockTypeface).withHeight(28.0f);
            bodyFont    = juce::Font(shockTypeface).withHeight(14.0f);
            labelFont   = juce::Font(horrorTypeface).withHeight(11.0f);
            smallFont   = juce::Font(horrorTypeface).withHeight(9.0f);
        }

        juce::Typeface::Ptr loadTypeface(const juce::String& name,
                                          const void* data, int size)
        {
            auto stream = std::make_unique<juce::MemoryInputStream>(data, size, false);
            auto tf = juce::Typeface::createSystemTypefaceFor(*stream);
            if (tf == nullptr)
            {
                // fallback
                tf = juce::Typeface::createSystemTypefaceFor(juce::Font(juce::Font::defaultSansSerifFontName, 12));
            }
            return tf;
        }

        juce::Typeface::Ptr shockTypeface;
        juce::Typeface::Ptr horrorTypeface;
        juce::Font displayFont;
        juce::Font bodyFont;
        juce::Font labelFont;
        juce::Font smallFont;
    };
}
